# 配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: springbootTest
    password: test

jpa:
  hibernate:
    ddl-auto: update # 第一次建表用 create 后面用 update（注意，如果通过jpa在数据库中建表，将jpa.hibernate,ddl-auto改为create，建完表之后，要改为update,要不然每次重启工程会删除表并新建。）
  showsql: true